# Generated by Django 3.1 on 2020-08-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0002_auto_20200810_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntity',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='income_calculator.basicmodel')),
                ('event_id', models.PositiveIntegerField()),
                ('item_id', models.PositiveIntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('expectation_value', models.IntegerField()),
                ('default_total', models.IntegerField()),
            ],
            bases=('income_calculator.basicmodel',),
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='income_calculator.basicmodel')),
            ],
            bases=('income_calculator.basicmodel',),
        ),
        migrations.RemoveField(
            model_name='event',
            name='default_total',
        ),
        migrations.RemoveField(
            model_name='event',
            name='expectation_value',
        ),
        migrations.RemoveField(
            model_name='event',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max',
        ),
        migrations.RemoveField(
            model_name='event',
            name='min',
        ),
        migrations.AddField(
            model_name='event',
            name='event_group_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
